name: Lockage
version: '1.0.0'
main: com.koopalabs.lockage.Lockage
api-version: '1.20'
author: Koopa
description: A chest locking system using tripwire hooks as keys

commands:
  lockage:
    description: Shows plugin help and admin commands
    usage: /<command> [reload]

permissions:
  lockage.use:
    description: Allows players to use basic locking features
    default: true
  lockage.admin:
    description: Allows access to admin commands
    default: op 